language: cpp
dist: xenial
compiler:
  - gcc
before_script:
  - export CC=gcc-9
  - export CXX=g++-9
script:
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd build && cmake --build .
env:
  - BUILD_TYPE=DEBUG
  - BUILD_TYPE=RELEASE
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

